# Упражнения по NumPy

Давайте проверим Ваши знания NumPy. Мы начнём с достаточно простых задач, и плавно перейдём к более сложным.

<div class="alert alert-danger" style="margin: 10px"><strong>ВАЖНОЕ ЗАМЕЧАНИЕ!</strong> Пожалуйста не запускайте ячейки, которые располагаются <br> непосредственно над ожидаемым результатом, иначе Вы удалите этот ожидаемый результат!</div>

#### 1. Импортируйте NumPy as np

In [1]:
import numpy as np

#### 2. Создайте массив из 10 нулей

In [3]:
# Напишите Ваше решение в этой ячейке
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Создайте массив из 10 единиц

In [5]:
# Напишите Ваше решение в этой ячейке
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Создайте массив из 10 пятёрок

In [6]:
# Напишите Ваше решение в этой ячейке
arr = np.full(10, 5)
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Создайте массив целых чисел от 10 до 50 включительно

In [8]:
# Напишите Ваше решение в этой ячейке
arr = np.arange(10, 51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Создайте массив всех чётных чисел от 10 до 50 включительно

In [9]:
# Напишите Ваше решение в этой ячейке
arr = np.arange(10, 51, 2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Создайте матрицу 3x3 со значениями от 0 до 8 включительно

In [10]:
# Напишите Ваше решение в этой ячейке
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Создайте единичную матрицу размером 3x3

In [12]:
# Напишите Ваше решение в этой ячейке
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. С помощью NumPy сгенерируйте случайное число в диапазоне от 0 до 1<br><br>&emsp;Замечание: Ваш результат может отличаться от того, что указано в качестве примера ниже.

In [28]:
# Напишите Ваше решение в этой ячейке
random_number = np.random.rand(1)
random_array = np.array(random_number)
random_array

array([0.15599452])

In [21]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([0.49658765])

#### 10. С помощью NumPy сгенерируйте массив из 25 случайных чисел, выбранных из стандартного нормального распределения<br><br>&emsp;&ensp;Замечание: Ваш результат может отличаться от того, что указано в качестве примера ниже.

In [23]:
# Напишите Ваше решение в этой ячейке
random_array = np.random.randn(25) #среднее = 0, стандартное отклонение = 1
random_array

array([-0.53965823,  0.00568342,  0.67344703,  0.55741778,  0.39326975,
       -0.1581775 ,  0.11749056, -0.97049981, -0.40931506,  3.69775775,
        0.67156249,  2.60896888,  2.56687826,  0.90648325, -0.56532339,
       -0.56606907,  0.77027727, -1.06467947,  0.35127394, -0.324184  ,
       -0.55453465,  1.62363058,  2.03269637, -0.85337084,  0.75590694])

In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 11. Создайте указанную ниже матрицу:

In [32]:
# Напишите Ваше решение в этой ячейке
arr = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 12. Создайте массив из 20 равноудалённых друг от друга точек между 0 и 1:

In [34]:
# Напишите Ваше решение в этой ячейке
arr = np.linspace(0, 1, 20)
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Индексация Numpy

Здесь Вы будете работать с некоторой матрицей - чтобы создать её, запустите следующую ячейку! После этого мы попросим Вас воспроизвести несколько результатов работы с этой матрицей:

In [35]:
# ЗАПУСТИТЕ ЭТУ ЯЧЕЙКУ - ЭТО СОЗДАНИЕ МАТРИЦЫ ДЛЯ СЛЕДУЮЩИХ ЗАДАНИЙ
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу (подсказка - используйте индексацию).

In [36]:
# Напишите Ваше решение в этой ячейке
mat[2::, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [37]:
# Напишите Ваше решение в этой ячейке
mat[3, -1]

20

In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


20

#### 15. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [42]:
# Напишите Ваше решение в этой ячейке
# mat[:3, 1]
mat[:3, 1][:, np.newaxis] # создаем новое измерение в массиве

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([[ 2],
       [ 7],
       [12]])

#### 16. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [43]:
# Напишите Ваше решение в этой ячейке
mat[-1]

array([21, 22, 23, 24, 25])

In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([21, 22, 23, 24, 25])

#### 17. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [48]:
# Напишите Ваше решение в этой ячейке
mat[3::]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Операции в NumPy

#### 18. Найдите сумму всех чисел в матрице mat

In [51]:
# Напишите Ваше решение в этой ячейке
total_sum = np.sum(mat)

total_sum

325

In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


325

#### 19. Найдите среднеквадратичное отклонение значений в матрице mat

In [53]:
# Напишите Ваше решение в этой ячейке
std_deviation = np.std(mat) #используем функцию np.std()

std_deviation

7.211102550927978

In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


7.211102550927978

#### 20. Найдите сумму каждой из колонок в матрице mat

In [55]:
# Напишите Ваше решение в этой ячейке
column_sums = np.sum(mat, axis=0)

column_sums

array([55, 60, 65, 70, 75])

In [56]:
# Напишите Ваше решение в этой ячейке
# 2ой способ
sum(mat) 

array([55, 60, 65, 70, 75])

In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([55, 60, 65, 70, 75])

## Бонусный вопрос

Мы много работали со случайными данными в numpy, но есть ли способ каждый раз получать одни и те же "случайные" результаты? [Для подсказки нажмите здесь](https://www.google.com/search?q=numpy+random+seed&rlz=1C1CHBF_enUS747US747&oq=numpy+random+seed&aqs=chrome..69i57j69i60j0l4.2087j0j7&sourceid=chrome&ie=UTF-8)

In [29]:
# Напишите Ваше решение в этой ячейке
np.random.seed(42)  # seed используется для генерации одинаковой последовательности случайных чисел

random_array = np.random.rand(5)  #теперь получаем одни и те же случайные числа
random_array 

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

# Отличная работа!

## Спасибо, удачного дня!